### PR TITLE
Create Locations utilities.

### PR DESCRIPTION
**Pull request by angelozerr**
Create Locations utilities.

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
> Why don’t you make this a method on LocationLink? Or a constructor on Location?

I didn't want to pollute some classes with another, but if you prefer I do that, I can change my PR.

**Comment by jonahgraham** [comment]
Hello folks, what is the state of this PR. We only have a short time before 0.9.0 release.

**Comment by spoenemann** [comment]
I think such conversion methods could be included in the protocol classes as proposed by @szarnekow. For example, this could be the Xtend code if added to `LocationLink`:

```xtend
def Location toLocation() {
    new Location(targetUri, targetRange)
}
```

@angelozerr are you going to continue this? Otherwise I'd close the PR.

**Comment by angelozerr** [comment]
No sorry, please close it and do an another PR if you wish.

**Pull request closed without merging**
