### PR TITLE
Change type of CodeLensOptions.resolveProvider to Boolean

### LINKED ISSUE #533: CodeLensOptions.resolveProvider should be Boolean
Currently, `CodeLensOptions.resolveProvider` is `boolean` in LSP4J. However, it should be `Boolean` according to the spec:

```ts
export interface CodeLensOptions extends WorkDoneProgressOptions {
	/**
	 * Code lens has a resolve provider as well.
	 */
	resolveProvider?: boolean;
}
```

Notably, `CodeLensRegistrationOptions.resolveProvider` is already `Boolean`.

### PR DESCRIPTION
**Pull request by pisv**
Fixes #533

### CODE REVIEW

**Comment by jonahgraham** [comment]
LGTM.

**Comment by pisv** [comment]
Thanks for the review Jonah! I believe it's simple enough to be merged without delay, isn't it?

**Review by KamasamaK — APPROVED** [review]

**Comment by jonahgraham** [comment]
> Thanks for the review Jonah! I believe it's simple enough to be merged without delay, isn't it?

Yes

**Comment by pisv** [comment]
Done. Thanks @KamasamaK for the review and approval.

**Pull request merged**
