### PR TITLE
Parse Object into a JsonElement in Either too

### LINKED ISSUE #524: Parse Object into a JsonElement in Either too
When `JsonElementTypeAdapter` was introduced in #154, `CollectionTypeAdapter` has been appropriately modified to make use of it, but `EitherTypeAdapter` has not.

Consequently, `List<Object>` is parsed into a list of JsonElements, but e.g. the right side of `Either<Boolean, Object>` (as in `SemanticTokensWithRegistrationOptions.range`) would currently be parsed into a map.

PR is coming.

### PR DESCRIPTION
**Pull request by pisv**
Fixes #524

Signed-off-by: Vladimir Piskarev <pisv@1c.ru>

### CODE REVIEW

**Comment by jonahgraham** [comment]
@eclipse-lsp4j-bot run tests

**Comment by pisv** [comment]
PR is ready for review. Thanks!

**Comment by jonahgraham** [comment]
Thanks @pisv - this looks fine to me. I hope someone from the LSP side can review if more reviewing is needed.

@eclipse-lsp4j-bot ok to test

**Comment by pisv** [comment]
Thank you Jonah!

**Comment by jonahgraham** [comment]
@pisv - feel free to use your new powers and merge (squash and merge is my preference, but there is no official policy for LSP4J). 

Feel free to add yourself to the admin list on https://ci.eclipse.org/lsp4j/job/lsp4j-github-pullrequests/configure so that you can run other contributors tests and so that yours run automatically.

Let me know if there is anything else I can do to help bring you up to speed.

**Comment by pisv** [comment]
Done!

Thanks Jonah! I really appreciate your help.

**Pull request merged**
