### PR TITLE
Fix type adapter for `workspace/diagnostic` response

### LINKED ISSUE #682: `JsonParseException: Ambiguous Either type` when reading response to `workspace/diagnostic`
I've just found this bug, which was supposed to be fixed as part of #668, but unfortunately it was not. `JsonParseException: Ambiguous Either type: token BEGIN_OBJECT matches both alternatives` is still thrown when reading a response to a `workspace/diagnostic` request.

The reason is that `WorkspaceDocumentDiagnosticReportTypeAdapter` was (erroneously) specified as `@ResponseJsonAdapter` for the `WorkspaceService.diagnostic` method, which actually returns a `WorkspaceDiagnosticReport` rather than  a `WorkspaceDocumentDiagnosticReport`.  I guess that this was unfortunate misreading caused by similarity in type names, since the wrong expected type was also used in the unit tests for parsing `workspace/diagnostic` response.

I'm preparing a PR to fix this.

### PR DESCRIPTION
**Pull request by pisv**
Fixes #682

### CODE REVIEW

**Comment by pisv** [comment]
Build failed with `[ERROR] Failed to resolve target definition /home/jenkins/agent/workspace/lsp4j-github-pullrequests/releng/releng-target/lsp4j.target.target: Could not find "com.google.guava/30.1.0.v20210127-2300" in the repositories of the current location`. I've provided a separate PR #684 to fix it.

**Comment by pisv** [comment]
Everything seems to be OK now. The PR is ready for review.

**Review by jonahgraham — APPROVED** [review]
This looks ok to me.

**Comment by pisv** [comment]
@jonahgraham Thanks for your review and approval! If there are no objections, I'm going to merge it tomorrow morning (European time).

**Comment by jonahgraham** [comment]
> @jonahgraham Thanks for your review and approval! If there are no objections, I'm going to merge it tomorrow morning (European time).

Perfect - works for me as I will probably do releng afternoon Ottawa time.

**Pull request merged**
