### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by michaellilltokiwa**
add java syntax highlighting for example section.

### CODE REVIEW

**Comment by dhuebner** [comment]
@michaellilltokiwa 
Thanks for contributing! 

You need to do the legal agreement here. See Failed Check:
Bildschirmfoto 2021-08-11 um 11 04 47

Click "Details" and follow the instructions. You need to do it only once.

Otherwise I can't merge your PR :(

**Comment by michaellilltokiwa** [comment]
@dhuebner Done. But unsure if it worked... I got redirected back to github.

**Comment by dhuebner** [comment]
@michaellilltokiwa 
I think you need to use the same email address as for github, otherwise it might not work.

In the past one needed to put also the `Signed-off-by: Humpty Dumpty <humpty.dumpty@example.com>`  Line in the bottom of the commit message. Again the email must be the same as the registered in Github and eclipse. But I think in the meantime it should work out of the box for ECA.

**Comment by michaellilltokiwa** [comment]
@dhuebner I used the same email address.

**Comment by dhuebner** [comment]
@michaellilltokiwa 
I see this status for your commit:
Bildschirmfoto 2021-08-11 um 13 02 01

If you have an account and signed the CA like described here https://wiki.eclipse.org/Development_Resources/Contributing_via_Git#Eclipse_Contributor_Agreement then it should work. Probably we need to contact eclipse support.  

I don't know if `*.noreply` is just a try to hide your real email address or not?

**Comment by pisv** [comment]
Please note that the author field of the [commit](https://github.com/eclipse/lsp4j/commit/9bd367c32a7696639d4389a61b7bdf25aedea7e2.patch) is currently not in the form required by the Eclipse Foundation: https://www.eclipse.org/projects/handbook/#resources-commit. The commit should be amended.

@michaellilltokiwa Please be sure to add your real name to your GitHub profile and also to not keep your email address private. See https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/managing-email-preferences/setting-your-commit-email-address for details. After that, I think that it would be easier to just close this PR and open another. Thanks for contributing!

**Comment by michaellilltokiwa** [comment]
@dhuebner @pisv I see, I did the edit via github web interface. Seems that I would need to change the github settings "Keep my email addresses private" and redo commit. Therefore closing this PR.

**Comment by dhuebner** [comment]
A good example why people stop contributing to open source. Literally for four letters change such a bureaucratic overhead :-(

**Comment by michaellilltokiwa** [comment]
@dhuebner I think there is an upside to this as well. Not everyone can submit just about everything all the time. There should be barriers when contributing to open source. Just not sure if this case is a good example for a reasonable entry barrier...

**Comment by dhuebner** [comment]
@michaellilltokiwa 
If I see it correctly you created a github account just for that change, right? You created a PR, you are waiting for approval communicating. I mean is that not already enough barriers? 
Maybe I just an old nagging man, so nevermind. Keep contributing and have fun!

**Comment by pisv** [comment]
It would be good to have a special case in the process for accepting a _trivial change_, but unfortunately there is no such currently.

**Pull request closed without merging**
