### PR TITLE
Fix equals for Either to handle null for both left and right

### PR DESCRIPTION
**Pull request by praksb**

### CODE REVIEW

**Comment by jonahgraham** [comment]
ok to test

**Comment by jonahgraham** [comment]
@praksb Please sign the [ECA](https://github.com/eclipse/lsp4j/blob/master/Contributing.md#eca) and Sign-off your commits (`git commit --amend --signoff`) so that you can pass ip-validation.

**Comment by jonahgraham** [comment]
There may be a shorter way to write it though:

```java
return Object.equals(this.left, other.left) || Object.equals(this.right, other.right);
```

I'll leave @spoenemann for final say on this.

**Comment by praksb** [comment]
Moved the tests.

**Comment by praksb** [comment]
I think I signed-off correctly on the commits. Not sure why ip-validation still fails.

**Comment by jonahgraham** [comment]
> I think I signed-off correctly on the commits. Not sure why ip-validation still fails.

It looks like the lines are inconsistent. Try using the built-in mechanism in git (--signoff command line). Your commits must have the same author as signed-off-by (e.g. your author is @ salesforce, but your signed off is @ gmail). 

I recommend squashing your commits, re-sign them with git --signoff and force push them.

**Comment by spoenemann** [comment]
Please merge this today (or latest on Sunday) if you want it in v0.5.0.

**Comment by praksb** [comment]
I am on vacation and I can take a look at the signing issue only after I get back on Monday.

**Comment by praksb** [comment]
@spoenemann can you take a look and approve if it looks good now? I believe the signing issue is now resolved.

**Comment by spoenemann** [comment]
Thanks!

**Pull request merged**
