### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by fredg1**
note about the signature of the releases and snapshots

### CODE REVIEW

**Comment by jonahgraham** [comment]
@fredg1 Thanks for the PR.

Hopefully this is the first of many :-) All contributors to LSP4J must sign the ECA: https://github.com/eclipse/lsp4j/blob/master/Contributing.md#eca

Please let me know if you have any questions.

**Comment by fredg1** [comment]
Is there a way to trigger the check again? I have finished signing the ECA

**Comment by fredg1** [comment]
no problem with that

**Comment by jonahgraham** [comment]
Thanks @fredg1!

**Pull request merged**
