### PR TITLE
update to guava 30.1

### LINKED ISSUE #497: Follow Orbit guava update
Eclipse Orbit plans to drop guava 27.1 and replace it with 30.1
https://bugs.eclipse.org/bugs/show_bug.cgi?id=570581
we should at least widen our ranges so that we can work with 30.1 too

### PR DESCRIPTION
**Pull request by cdietrich**
update to guava 30.1
Fixes #497

Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by cdietrich** [comment]
log has something like

```

06:42:50  [INFO] --- tycho-p2-publisher-plugin:1.5.1:attach-artifacts (default-attach-artifacts) @ lsp4j.p2-repository ---
06:42:50  [INFO] 
06:42:50  [INFO] --- tycho-p2-repository-plugin:1.5.1:assemble-repository (default-assemble-repository) @ lsp4j.p2-repository ---
06:42:50  [WARNING] Mirror tool: Problems resolving provisioning plan.: [Unable to satisfy dependency from v20210201-0541.Default 1.0.0.9r5-cKYB3-E81DZUMEMMz07QkYE to org.eclipse.equinox.p2.iu; com.google.guava [30.1.0.v20210127-2300,30.1.0.v20210127-2300].]
06:42:50  [WARNING] More information on the preceding warning(s) can be found here:
06:42:50  [WARNING] - http://wiki.eclipse.org/Tycho_Messages_Explained#Mirror_tool
06:42:50  [WARNING] Mirror tool: Problems resolving provisioning plan.: [Unable to satisfy dependency from v20210201-0541.Default 1.0.0.9r5-cKYB3-E81DZUMEMMz07QkYE to org.eclipse.equinox.p2.iu; com.google.guava [30.1.0.v20210127-2300,30.1.0.v20210127-2300].]
06:42:50  [WARNING] More information on the preceding warning(s) can be found here:
06:42:50  [WARNING] - http://wiki.eclipse.org/Tycho_Messages_Explained#Mirror_tool
06:42:50  [WARNING] Mirror tool: Problems resolving provisioning plan.: [Unable to satisfy dependency from v20210201-0541.Default 1.0.0.9r5-cKYB3-E81DZUMEMMz07QkYE to org.eclipse.equinox.p2.iu; com.google.guava [30.1.0.v20210127-2300,30.1.0.v20210127-2300].]
06:42:50  [WARNING] More information on the preceding warning(s) can be found here:
06:42:50  [WARNING] - http://wiki.eclipse.org/Tycho_Messages_Explained#Mirror_tool
```

dont know where this is coming from

**Comment by cdietrich** [comment]
also the update site looks wired


com.google.guava_27.1.0.jre.jar | 01.02.2021 00:42:56 | 2.62 MB | anzeigen
-- | -- | -- | --
  | com.google.guava.source_30.1.0.v20210127-2300.jar | 01.02.2021 00:42:56 | 1.70 MB | anzeigen

**Comment by cdietrich** [comment]
looks like i have a fix for that now

**Review by jonahgraham — APPROVED** [review]
@cdietrich  LGTM.

**Pull request merged**
