### PR TITLE
TextDocumentSyncOptions.save is either Boolean or SaveOptions

### LINKED ISSUE #426: LSP4J fails to parse TextDocumentSyncOptions with a boolean value for property `save`
The type `TextDocumentSyncOptions` is defined as follows in the LSP spec:

```typescript
export interface TextDocumentSyncOptions {
	...
	save?: boolean | SaveOptions;
}
```

However, LSP4J doesn't handle boolean values, only `SaveOptions`.

Note that this may stem from a slight inconsistency in the LSP spec, which got resolved only quite recently. See also https://github.com/microsoft/language-server-protocol/issues/989

### PR DESCRIPTION
**Pull request by planger**
Fixes #426

Signed-off-by: Philip Langer <planger@eclipsesource.com>

### CODE REVIEW

**Comment by jonahgraham** [comment]
@eclipse-lsp4j-bot run tests

**Comment by aarcangeli** [comment]
Can we merge? I'm having this problem too.
Is there a temporary workaround?

**Comment by planger** [comment]
> Can we merge? I'm having this problem too.

There is a discussion on how to deal with API breaks [1]. As far as I can see, there is some feedback to be in favor of accepting API breaks between minor versions, iff they only reflect LSP spec changes. So I guess this would mean we could merge this change. @jonahgraham what do you think?

> Is there a temporary workaround?

No, none that I'm aware of. I worked around it only by patching LSP4J as a temporary solution.

[1] https://www.eclipse.org/lists/lsp4j-dev/msg00049.html

**Comment by jonahgraham** [comment]
I think we should merge this change and schedule a release. There are a number of outstanding items waiting for a release.

**Comment by cdietrich** [comment]
we also might need a review for the release as the last is >12 month ago

**Comment by aarcangeli** [comment]
Thank you, I just built by myself jars the from master branch and everything is working fine.

**Pull request merged**
