### PR TITLE
Update Javadoc of Variable#type

### PR DESCRIPTION
**Pull request by gquerret**
The Variable#type javadoc does not seem correct to me. I've changed the documentation to match the [DAP specification](https://microsoft.github.io/debug-adapter-protocol/specification#Types_Variable)

### CODE REVIEW

**Review by jonahgraham — APPROVED** [review]
Thanks - this change is good. Now lets see if we can figure out what is going wrong with ECA.

**Comment by jonahgraham** [comment]
@eclipse-lsp4j-bot run tests

**Comment by gquerret** [comment]
I've opened a ticket, as I'm not able to regain access to the `gquerret` account.

**Comment by jonahgraham** [comment]
Thanks @gquerret for persisting in sorting out the ECA issues. I hope that now we have been through this once you will find it smoother and faster to make PRs in the future.

**Comment by gquerret** [comment]
All in all, it wasn't very difficult and got very good help from the Eclipse team. I'll open new PR if I find anything worth a modification !

**Pull request merged**
