### PR TITLE
Updated significant portion for LSP 3.15

### PR DESCRIPTION
**Pull request by KamasamaK**
I went through most of the [LSP 3.15](https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/) changes and below is the summary of my changes:

* Removed `@Beta`from `textDocument/selectionRange` items
* Add support for server and client information.
* Add signature help context.
* Fixed `version` on `PublishDiagnosticsParams`  (see below) and added missing client capability.
* Add CodeAction#isPreferred support.
* Add CompletionItem#tag support.
* Add DocumentLink#tooltip support.
* Add trimTrailingWhitespace, insertFinalNewline and trimFinalNewlines to FormattingOptions.
* Clarified WorkspaceSymbolParams#query parameter.
* Deprecated `MarkedString`
* Deprecated `rangeLength` in `TextDocumentContentChangeEvent`
* Misc. spelling/grammar fixes

Breaking API changes (stable):
 * `valueSet` of `CodeActionKindCapabilities` set to `@NonNull`
 * Signature of `textDocument/signatureHelp` changed from `signatureHelp(TextDocumentPositionParams position)` to `signatureHelp(SignatureHelpParams params)`

Breaking API changes (preview):
 * `valueSet` of `DiagnosticTagSupport` set to `@NonNull`
 * `version` of `PublishDiagnosticsParams` changed from `int` to `Integer`

Still missing for complete 3.15:
 * [General Progress Support](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#progress)
 * [Work Done Progress](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workDoneProgress)
 * [Partial Result Progress](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#partialResults)

### CODE REVIEW

**Comment by jonahgraham** [comment]
@KamasamaK I have [added you](https://ci.eclipse.org/lsp4j/job/lsp4j-github-pullrequests/jobConfigHistory/showDiffFiles?timestamp1=2019-11-25_15-32-52&timestamp2=2020-01-20_14-29-53) to the whitelist so your PRs should build automatically in the future.

**Comment by spoenemann** [comment]
@KamasamaK would you like to become a project committer?

See https://projects.eclipse.org/projects/technology.lsp4j/who

**Comment by jonahgraham** [comment]
I am not sure what, if anything, prevented @spoenemann from merging this after reviewing it successfully. But this gives us a chance to fix up some administrative stuff in the commits.

**Comment by KamasamaK** [comment]
@spoenemann 
> @KamasamaK would you like to become a project committer?

Sure. What is the process for that?


@jonahgraham I think I addressed all the issues you mentioned.

**Comment by jonahgraham** [comment]
Thanks @KamasamaK - I will merge this tomorrow and then apply the downstream changes to LSP4E I have lined up to fix the API changes.

----

I am very grateful for the thoroughness of your reviews and think you would be a good addition to the LSP4J project. As for process @spoenemann will create a new committer vote with the justifaction/contributions you have done and the existing committers and project management committee (PMC) will vote. You can read the full process here https://www.eclipse.org/projects/handbook/#elections-committer - although it may be best to continue this conversation on the lsp4j-dev mailing list rather than hiding it within this PR :-)

**Comment by spoenemann** [comment]
> As for process @spoenemann will create a new committer vote with the justifaction/contributions you have done and the existing committers and project management committee (PMC) will vote.

The process has started. @KamasamaK would you mind changing your [Eclipse profile](https://projects.eclipse.org/user/13977) so it includes your real name? This is important for transparency of the project, see https://projects.eclipse.org/projects/technology.lsp4j/who

**Comment by jonahgraham** [comment]
https://github.com/eclipse/lsp4j/issues/369#issuecomment-580216982

@KamasamaK please see above q from 
@cdietrich

**Comment by jonahgraham** [comment]
> > As for process @spoenemann will create a new committer vote with the justifaction/contributions you have done and the existing committers and project management committee (PMC) will vote.
> 
> The process has started. @KamasamaK would you mind changing your [Eclipse profile](https://projects.eclipse.org/user/13977) so it includes your real name? This is important for transparency of the project, see https://projects.eclipse.org/projects/technology.lsp4j/who

@spoenemann should the election be restarted after the name has been updated otherwise the election will have the pseudonym in the URL: https://projects.eclipse.org/projects/technology.lsp4j/elections/election-kama-sama-committer-eclipse-lsp4j - I am +1 aside from this

**Comment by KamasamaK** [comment]
@spoenemann @jonahgraham I tried to change that profile a few days ago and again just now, but it's been unsuccessful. When saving the changes, I get logged out and shown a message that says "A password request change has been submitted for your Eclipse account. Please try to login with your new password." and when logging back in (with the same password) nothing changed.

I agree with @jonahgraham that this should probably not be in the PR but this tech support issue doesn't exactly seem appropriate for the lsp4j-dev mailing list either.

**Comment by jonahgraham** [comment]
OK - well lets continue here for now :-) Can you email webmaster@eclipse.org and request your account name be fixed please?

**Comment by KamasamaK** [comment]
The name on my account has been updated.

**Comment by spoenemann** [comment]
> This election failed to receive the required number of votes in the alotted time.

I'm starting a new one.

**Pull request merged**
