### PR TITLE
Add inlay hint support

### PR DESCRIPTION
**Pull request by KamasamaK**
Adds inlay hint support which is currently proposed for LSP 3.17

### CODE REVIEW

**Comment by nixel2007** [comment]
First naive implementation for BSL Language Server. Thanks a lot, @KamasamaK!
image

**Comment by mickaelistria** [comment]
That's a feature we'd love to integrate ASAP in LSP4E, and the current patch seems correct. We'd appreciate if it can be merged and then released soon-ish ;)

**Comment by angelozerr** [comment]
+1, JDT LS and Qute LS require this PR. Today they use their own InlayHint Java class, but when LSP4J wil be released with this InlayHint support we could remove those cutsom class.

**Comment by mickaelistria** [comment]
Thanks @KamasamaK !

**Pull request merged**
