### PR TITLE
Fixed guava version problem

### LINKED ISSUE #374: Update site does not repackage guava
Update site does not repackage guava. this prevents us from fixing the mwe update site
https://github.com/eclipse/mwe/issues/89
see also https://github.com/eclipse/lsp4j/issues/359

### PR DESCRIPTION
**Pull request by cdietrich**
Fixed guava version problem
fixes #374

Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by jonahgraham** [comment]
I added the p2 repo build step to the PR builder CI job, so rerun tests

**Comment by cdietrich** [comment]
how can i do that?

**Comment by cdietrich** [comment]
will try this locally.

**Comment by jonahgraham** [comment]
"rerun tests" was a message for the CI bot.

**Comment by jonahgraham** [comment]
(which will probably do it again because of that message)

**Comment by cdietrich** [comment]
the problem is the xbase version that is still 2.18 :(

**Comment by cdietrich** [comment]
hmmm

```
[INFO] --- tycho-p2-repository-plugin:1.4.0:assemble-repository (default) @ lsp4j.p2-repository ---
[WARNING] Mirror tool: Problems resolving provisioning plan.: [Unable to satisfy dependency from v20191125-2040.Default 1.0.0.9P3-cKYB3-DUUEN2EkMg7N_Uo to org.eclipse.equinox.p2.iu; com.google.guava [27.1.0.v20190517-1946,27.1.0.v20190517-1946].]
[WARNING] More information on the preceding warning(s) can be found here:
[WARNING] - http://wiki.eclipse.org/Tycho_Messages_Explained#Mirror_tool
[WARNING] Mirror tool: Problems resolving provisioning plan.: [Unable to satisfy dependency from v20191125-2040.Default 1.0.0.9P3-cKYB3-DUUEN2EkMg7N_Uo to org.eclipse.equinox.p2.iu; com.google.guava [27.1.0.v20190517-1946,27.1.0.v20190517-1946].]
[WARNING] More information on the preceding warning(s) can be found here:
[WARNING] - http://wiki.eclipse.org/Tycho_Messages_Explained#Mirror_tool
[WARNING] Mirror tool: Problems resolving provisioning plan.: [Unable to satisfy dependency from v20191125-2040.Default 1.0.0.9P3-cKYB3-DUUEN2EkMg7N_Uo to org.eclipse.equinox.p2.iu; com.google.guava [27.1.0.v20190517-1946,27.1.0.v20190517-1946].]
[WARNING] More information on the preceding warning(s) can be found here:
[WARNING] - http://wiki.eclipse.org/Tycho_Messages_Explained#Mirror_tool

```

**Comment by cdietrich** [comment]
@jonahgraham please reexamine

**Comment by jonahgraham** [comment]
Other than the warnings you highlighted, lgtm.

**Pull request merged**
