### PR TITLE
fix #447 add progress on call hierarchy

### LINKED ISSUE #447: Add progress to Call Hierarchy
New Call hierarchy feature: https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/#textDocument_prepareCallHierarchy

More info on protocol here: https://github.com/microsoft/vscode-languageserver-node/blob/master/protocol/src/common/protocol.callHierarchy.ts

### PR DESCRIPTION
**Pull request by Dufgui**

### CODE REVIEW

**Comment by Dufgui** [comment]
During this, i discover there is 7 tests not working on master. I fix it their or in another merge request ? @spoenemann ?

**Comment by spoenemann** [comment]
It's ok to fix them in a separate PR if the tests are unrelated to these changes.

**Comment by Dufgui** [comment]
> 
> 
> It's ok to fix them in a separate PR if the tests are unrelated to these changes.

yes it's totally unrelated and already present on master. I will fix them

**Comment by Dufgui** [comment]
here is the fix on unit tests

https://github.com/eclipse/lsp4j/pull/451

**Review by spoenemann — APPROVED** [review]
Thanks!

**Comment by spoenemann** [comment]
@Dufgui could you try to "Rebase and merge" yourself? It should be possible now.

**Comment by Dufgui** [comment]
sorry but according to github "Pull request author cannot approve this own pull request"

**Comment by Dufgui** [comment]
And i don't think i have the right access because github display:
"Only those with write access to this repository can merge pull requests."

**Comment by spoenemann** [comment]
Maybe it just takes a bit more time until an Eclipse admin has given you the proper rights. Your committer election is already approved. Let's try again next time.

**Pull request merged**
