### PR TITLE
Update to DAP v1.35

### PR DESCRIPTION
**Pull request by KamasamaK**
The supported DAP is very outdated. I've gone through and made all of the necessary changes to bring it to the latest version v1.35.

### CODE REVIEW

**Comment by jonahgraham** [comment]
Commit 45105529d9a867c17d47e011999b9774424d95b2 looks good, in that it is signed off. Please force push that commit to your branch.

**Comment by KamasamaK** [comment]
I am trying to force push, but it just keeps saying "Everything up-to-date".

**Comment by KamasamaK** [comment]
@jonahgraham Thanks. I think I got it.

**Comment by jonahgraham** [comment]
ok to test

**Comment by jonahgraham** [comment]
Thank you @KamasamaK - I am really happy to have this in in time for the [0.8.0 release](https://projects.eclipse.org/projects/technology.lsp4j/releases/0.8.0) in a couple of weeks.

**Pull request merged**
