### PR TITLE
Fix inconsistencies in *RegistrationOptions

### LINKED ISSUE #481: Inconsistencies in *RegistrationOptions
Some of the `*RegistrationOptions` classes need to be made consistent with the current LSP specification.

Full list of classes to update:

- [ ] `CallHierarchyRegistrationOptions` - does not extend `StaticRegistrationOptions`
- [ ] `DeclarationRegistrationOptions` - does not extend `StaticRegistrationOptions`
- [ ] `DocumentSymbolRegistrationOptions` - missing `label`?: `string`
- [ ] `ImplementationRegistrationOptions` - does not extend `StaticRegistrationOptions`
- [ ] `SemanticTokensWithRegistrationOptions` - does not extend `StaticRegistrationOptions`
- [ ] `SignatureHelpRegistrationOptions` - missing `retriggerCharacters`?: `string[]`
- [ ] `TypeDefinitionRegistrationOptions` - does not extend `StaticRegistrationOptions`

### PR DESCRIPTION
**Pull request by pisv**
Fixes #481

Signed-off-by: Vladimir Piskarev <pisv@1c.ru>

### CODE REVIEW

**Comment by nixel2007** [comment]
I think tiu should run generator to apply changes from xtend to generated classes

**Comment by KamasamaK** [comment]
@nixel2007 Those were removed in #501

**Comment by nixel2007** [comment]
@KamasamaK my bad. Thanks!

**Comment by jonahgraham** [comment]
@eclipse-lsp4j-bot ok to test

**Comment by jonahgraham** [comment]
Hi folks, if someone with LSP knowledge can review this that would be greatly appreciated. If you do review ahead of me fixing #508 let me know and I can help make sure the tests pass. In the meantime, please disregard the failing "Jenkins PR Build" check.

**Review by KamasamaK — APPROVED** [review]

**Comment by jonahgraham** [comment]
@eclipse-lsp4j-bot rerun test

**Comment by jonahgraham** [comment]
@eclipse-lsp4j-bot  retest this please

**Pull request merged**
