### PR TITLE
Fix Contributing.md formatting

### PR DESCRIPTION
**Pull request by Marcono1234**
This properly indents nested entries in the "Eclipse" of Contributing.md.

I have not signed the Eclipse Contributor Agreement and am not planning to do this at the moment. Hopefully this is not an issue because this is only documentation related.  
However, if it is an issue, then feel free to close this pull request. I hereby grant you all rights for the proposed changes, feel free to apply them yourself.

### CODE REVIEW

**Comment by jonahgraham** [comment]
Hi @Marcono1234, Thank you for your contribution to fix up the documentation. 

Documentation is not excluded from IP process and requires a CQ. However I don't know if this change counts as IP, but I don't know what the process of overridding the "eclipsefdn/eca — The author(s) of the pull request is not covered by [...]" check.

Therefore if you are able to sign the ECA then that would mean I can accept the contribution immediately. If you want to reach out to me privately to discuss feel free to email me.

Thanks!

**Comment by Marcono1234** [comment]
Thank you for this information. I have written an e-mail to license@eclipse.org, but have not got a  response yet.
My questions are:
- Which Eclipse members (or member groups) will be able to see the personal information required for the ECA?
- Does the ECA work when using the `@users.noreply.github.com` mail address? https://bugs.eclipse.org/bugs/show_bug.cgi?id=496885#c24 suggests that might work when using the same name for the Eclipse account

It appears this is not covered in the [FAQ](https://www.eclipse.org/legal/ecafaq.php)

**Comment by jonahgraham** [comment]
Thanks for sending that email. The current process requires full name and email address, but I don't know if the masked email address is ok. 

From the [Developer Handbook](https://www.eclipse.org/projects/handbook/)

> The named used in the Author field (and, when required, in the Also-by and Signed-off-by fields) must be the legal name of the contributor; the email address must be valid and real.

**Comment by Marcono1234** [comment]
Thanks for the clarification. I am not going to sign the ECA then, sorry for the trouble this caused.

**Comment by jonahgraham** [comment]
Hi @Marcono1234 - I am sorry to be losing your contributions to the project. As such I have raised the issue of real names with the Eclipse Architecture Council who represent the community and work with the Eclipse Foundation on what the processes should be. While the mailing list is read-only for non-members, you can see my question and responses on https://www.eclipse.org/lists/eclipse.org-architecture-council/msg04183.html

**Comment by jonahgraham** [comment]
@Marcono1234 This topic is now on the agenda for our next call. If possible, can you provide a short explanation as to why you object to contributing with real name & address so that we can use this case as an example for our discussions? I notice that you have made contributions to other projects (e.g. https://github.com/google/gson/pull/1655) so I am wondering what may be different about Eclipse's one. Any input you have would be great so that the Eclipse Architecture Council can have a fruitful discussion.

e.g. the Google CLA says:

> By signing this contributor license agreement, I understand and agree that this project and contributions to it are public and that a record of the contribution (including all personal information I submit with it, including my full name and email address) is maintained indefinitely and may be redistributed consistent with this project, compliance with the open source license(s) involved, and maintenance of authorship attribution.

**Comment by Marcono1234** [comment]
Thank you for your commitment regarding this topic.

I am a reluctant to contribute with real name and address because I would like to keep my activity here separate from my other activities. Additionally I feel like the general concept of how e-mails work might not provide the necessary means to prevent unwanted mails so I would prefer to not have my e-mail address in the public.

While the Google CLA does indeed have the section quoted by you, I was not able to find a requirement that you must provide this personal information with commits. I understand it rather as "If you choose to provide this information, then ...". And looking at the other contributors of Gson, multiple do not provide personal information in their contributions. When signing the Google CLA you have to provide a "Name". It does not explicitly specify that this has to be the real name (maybe this is required somewhere else), though that might be implicit.

**Comment by jonahgraham** [comment]
Thanks @Marcono1234 - we have had our meeting on this and will be getting the handbook updated. The exact wording is to be determined, but the [summary](https://wiki.eclipse.org/Architecture_Council/Meetings/Meeting_Notes) of the call is:

> 
> Anonymous contributions (Jonah)
> - A GitHub account as contributor is ok, it can be traced back to an individual.
> - An ECA must be signed in any case. This requires a real email address and this is sufficient.
> - EMO expectation to committers is to monitor and catch/report shenanigans.
> - The handbook wording needs an updated and will investigated separately.

Therefore, if you are willing to sign the ECA then I can (happily!) accept your changes.

Thanks for your patience on this.

**Comment by Marcono1234** [comment]
Thanks for letting me know. But using the GitHub `@users.noreply.github.com` e-mail address is therefore not possible (at the moment), is that correct? And is it possible to create an Eclipse account without others being able to see your e-mail address? You can see the e-mail address of others when they interact with the Bugzilla bug tracker, but maybe this is even possible without any interaction on the bug tracker or any other Eclipse service.

**Comment by jonahgraham** [comment]
When you edit your Eclipse Profile there is a globe icon next to fields that are public. You can look at my profile https://accounts.eclipse.org/users/jograham to see what is public by default.

**Pull request closed without merging**
