### PR TITLE
Trace error response

### PR DESCRIPTION
**Pull request by adpi2**
Print the error of a `ResponseMessage` in the `TracingMessageConsumer`

### CODE REVIEW

**Comment by jonahgraham** [comment]
@eclipse-lsp4j-bot ok to test

**Review by jonahgraham — CHANGES_REQUESTED** [review]
Thanks @adpi2 for the change request. Including the error information in the trace is a good idea. Can you please add a test that has an error to show and test the error response working?

**Comment by jonahgraham** [comment]
@adpi2 Can you please sign off your commits and amend your existing one. e.g. do `git commit --amend --signoff` and then git push with a `--force` 

Additional information on contributing to Eclipse projects can be found on the Eclipse wiki under [Development Resources/Handling](https://wiki.eclipse.org/Development_Resources/Handling_Git_Contributions) Git Contributions, or under [Development Resources/Contributing via Git](https://wiki.eclipse.org/Development_Resources/Contributing_via_Git) for new committers.

thanks!

**Comment by adpi2** [comment]
Thank you @jonahgraham for your review.

I have added a test and signed my commits.

**Review by jonahgraham — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
