### PR TITLE
Fixed eclipse#324 Send empty string in query of workspace/symbol

### PR DESCRIPTION
**Pull request by jonas-jonas**
As mentioned in #324 this would fix the error by sending an empty string in the `query` param of `workspace/symbol`. I also locally tested it against our project.

### CODE REVIEW

**Comment by spoenemann** [comment]
I would prefer to have this fixed in the client implementation (LSP4E) instead of inducing a specific behavior in the default constructor.

**Comment by jonas-jonas** [comment]
While I agree, that this could be fixed in LSP4E, the fix would be passing an empty String to the constructor of `WorspaceSymbolParams`. Which seems kind of "hacky". 

Also the spec states that the `query` should not be empty: https://microsoft.github.io/language-server-protocol/specification#workspace_symbol
(which is currently being discussed: https://github.com/microsoft/vscode-languageserver-node/issues/458)

But in any case the `query` should not be omitted completely. Which means that the implementation in LSP4J is not according to the spec.

That being said, as I mentioned the fix in LSP4E would be rather trivial but "hacky". I just wanted to raise this here first.

**Comment by spoenemann** [comment]
> Which means that the implementation in LSP4J is not according to the spec.

You cannot expect to obtain a valid protocol object just by invoking the default constructor. The default constructor is rather meant for post-construction configuration, which can be done quite nicely in some Java-based languages. For example, in Xtend I'd rather write

```xtend
new WorkspaceSymbolParams => [
    query = "foo"
]
```

instead of using a constructor `new WorkspaceSymbolParams("foo")` because the constructor doesn't tell me to which properties its arguments are assigned. The Xtend syntax is closer to the TypeScript style object creation:

```typescript
<WorkspaceSymbolParams> {
    query: "foo"
}
```

Anyway, I'm not totally against initializing properties in the default constructor (this is already done in a few protocol classes, but it's very inconsistent... maybe worth a separate issue?), but I also don't think it would be "hacky" to call the constructor (or the `query` setter) with an empty string in the LSP4E client. In the pull request provided in the discussion you mentioned

https://github.com/microsoft/language-server-protocol/pull/770/files#diff-32fe5a6c631807387f43b01824ccea9d

the documentation is changed to

> A query string to filter symbols by. Clients may send an empty string here to request all symbols.

I understand this as the empty string having a special meaning in the protocol, so I think it's good if the client explicitly sets the property to `""` to show it's referring to that special meaning.

**Comment by jonas-jonas** [comment]
Alright, makes sense. Thanks for your quick and detailed answers. I will raise the issue with LSP4E. Closing.

**Pull request closed without merging**
