### PR TITLE
Fixes #432 - broken pipe (write failed) is also a stream closed excep…

### LINKED ISSUE #432: Broken pipe (Write failed) should be a connection-closed exception
JsonRpcException includes the following code:

```
	public static boolean indicatesStreamClosed(Throwable thr) {
		return thr instanceof InterruptedIOException
				|| thr instanceof ClosedChannelException
				|| thr instanceof IOException && "Pipe closed".equals(thr.getMessage())
				|| thr instanceof SocketException && ("Connection reset".equals(thr.getMessage()) || "Socket closed".equals(thr.getMessage()))
				|| thr instanceof JsonRpcException && indicatesStreamClosed(thr.getCause());
	}
```

"Broken pipe (Write failed)"  should be included in this list.

### PR DESCRIPTION
**Pull request by robstryker**
…tion

Signed-off-by: Rob Stryker <stryker@redhat.com>

### CODE REVIEW

**Comment by jonahgraham** [comment]
run tests

**Comment by jonahgraham** [comment]
Thank you @robstryker

**Comment by robstryker** [comment]
@jonahgraham  Any idea when next release is?

**Comment by jonahgraham** [comment]
No - it can be soon, but there is no plan. See https://www.eclipse.org/lists/lsp4j-dev/msg00073.html

**Comment by cdietrich** [comment]
do i assume correct we release lsp and dap in sync? lsp 3.16 does not seem to be out yet.

**Comment by jonahgraham** [comment]
> do i assume correct we release lsp and dap in sync? 

Yes.

> lsp 3.16 does not seem to be out yet.

OK - I assume with Miro's announcement this morning that isn't a concern. If so, we should continue the conversation there rather than this closed PR.

**Pull request merged**
