### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by spoenemann**
This is a preparation for the [upcoming release 0.10.0](https://projects.eclipse.org/projects/technology.lsp4j/releases/0.10.0). 

We should track all breaking changes. @KamasamaK @Dufgui @ericdallo could you help with this? Are you aware of any breaking changes that came with your contributions?

CC @jonahgraham

### CODE REVIEW

**Comment by ericdallo** [comment]
About semanticTokens side, AFAIK this would be the only breaking change: https://github.com/eclipse/lsp4j/issues/457 but it was not implemented yet (and maybe it should be for the next release?)

**Comment by jonahgraham** [comment]
Thanks @spoenemann for raising this. 

The readme also needs an update: https://github.com/eclipse/lsp4j/blob/0faac0cc5d1dc51f45b9c7540ad9b94eef38ddca/README.md#supported-lsp-versions

**Comment by KamasamaK** [comment]
The only potentially breaking change with my contributions is that `DocumentOnTypeFormattingParams` now extends `TextDocumentPositionParams` instead of `DocumentFormattingParams`. Also, `DocumentRangeFormattingParams` no longer extends `DocumentFormattingParams`. I doubt that would actually result in breaking anything, but I suppose it's possible.

**Comment by Dufgui** [comment]
I think I don’t have breaking change.
I only append fields or parent class. I don’t remove anything.

**Comment by spoenemann** [comment]
Thanks!

**Pull request merged**
