### PR TITLE
Cherry Picked Reflective Message Validator and Increased Version to 0.1.2-SNAPSHOT

### PR DESCRIPTION
**Pull request by cdietrich**
increased version to 0.1.2-SNAPSHOT

Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by cdietrich** [comment]
if i sign antons commits afterwards it seems to work

**Comment by akosyakov** [comment]
@svenefftinge Should https://github.com/eclipse/lsp4j/commit/b42c3030745ef733b7d1af684071884acb7cf72f also be included? most of stacktraces are swallowed here

**Comment by spoenemann** [comment]
Please don't merge this into the `release_0.1.1` branch, but create a new branch `maintenance_0.1` instead.

**Comment by cdietrich** [comment]
i actually cant? can i? 
=> can you create a branch that i can switch the pull request target,

**Comment by akosyakov** [comment]
@cdietrich I've created a new branch `maintenance_0.1`, please open a new PR against it. cc @spoenemann

**Comment by cdietrich** [comment]
I just updated this pullreq

**Pull request merged**
