### PR TITLE
fixed a NPE when writing null value of type Either to Json

### PR DESCRIPTION
**Pull request by peq**
I ran into this NPE when I did not set `TextDocumentSync` on the capabilities.

### CODE REVIEW

**Comment by spoenemann** [comment]
Thanks!

**Comment by JiahuiJiang** [comment]
@spoenemann Can we have a new release cut with this fix inside? :) We are migrating from typefox-lsapi and this NPE is blocking the migration

**Comment by spoenemann** [comment]
Yes, we could release 0.2.1 soon.

**Comment by spoenemann** [comment]
> Yes, we could release 0.2.1 soon.

Done.

**Pull request merged**
