### PR TITLE
Fix ambiguous Either type when parsing unresolved code action

### LINKED ISSUE #484: Ambiguous Either type when parsing unresolved code action
LSP 3.16 added support for code action [resolving](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#codeAction_resolve). Currently, `CodeActionResponseAdapter` assumes that a code action must set either `edit` and/or a `command` property. This assumption no longer holds for an unresolved code action. An unresolved code action may be as simple as `{ "title": "Do Foo" }`. Parsing a code action response with such a code action leads to
```
com.google.gson.JsonParseException: Ambiguous Either type: token BEGIN_OBJECT matches both alternatives.
	at org.eclipse.lsp4j.jsonrpc.json.adapters.EitherTypeAdapter.create(EitherTypeAdapter.java:188)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.EitherTypeAdapter.read(EitherTypeAdapter.java:172)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.EitherTypeAdapter.read(EitherTypeAdapter.java:1)
```

### PR DESCRIPTION
**Pull request by pisv**
Fixes #484

Signed-off-by: Vladimir Piskarev <pisv@1c.ru>

### CODE REVIEW

**Comment by pisv** [comment]
Could someone please review/merge this PR before the 0.11.0 release? It is related to LSP 3.16 support and the issue seems to be easy to fix. Thanks!

**Review by KamasamaK — APPROVED** [review]
Unfortunately, `CodeAction` doesn't appear to have a good, unique check. But since `leftChecker` is tested first, this should be good.

**Comment by jonahgraham** [comment]
Thanks @pisv for the fix and @KamasamaK for the review.

**Comment by pisv** [comment]
Thanks for reviewing and merging!

**Pull request merged**
