### PR TITLE
Late updates for LSP 3.17

### PR DESCRIPTION
**Pull request by KamasamaK**
These are the changes to the LSP 3.17 specification that were added after it was published as done.

### CODE REVIEW

**Comment by jonahgraham** [comment]
We can spin up a 0.14.0 release if needed in short order, please let me know with a comment on #628

**Comment by cdietrich** [comment]
i assume a 0.13.1 would be better for p2 consumers
as maven consumers a rebuild would be needed anway

**Comment by jonahgraham** [comment]
> i assume a 0.13.1 would be better for p2 consumers as maven consumers a rebuild would be needed anway

I advise against it because there are API changes in this commit - 0.13.0 and 0.13.1 are not interchangeable due to new fields and the changed super type hierarchy. I could be convinced otherwise though if you think it is unlikely enough for anyone to hit that problem in practice, especially as we are still officially incubating.

**Comment by cdietrich** [comment]
Yes. The question is when it would be available. I planned to do a Xtext release on Monday

**Comment by jonahgraham** [comment]
@cdietrich I can release very quick once it is merged as I just went through the cycle of that a few days ago. Can you or @KamasamaK  or someone else approve and merge?

**Review by jonahgraham — APPROVED** [review]

**Review by cdietrich — APPROVED** [review]

**Pull request merged**
