### PR TITLE
Update to Gradle 7.5 and xtend-gradle-plugin 3.0.2

### PR DESCRIPTION
**Pull request by cdietrich**
Update to Gradle 7.5 and xtend-gradle-plugin 3.0.2
Added missing resources.prefs

### CODE REVIEW

**Comment by cdietrich** [comment]
@jonahgraham the PR build still seems to execute
createLocalMavenRepo
where is this one defined?

**Comment by cdietrich** [comment]
it seems to be in the config, edited it. lets see

**Review by jonahgraham — APPROVED** [review]
This seems fine to me, I haven't reviewed a diff of the outputs, let me know if you need me to do that again.

PS Can you add something to the Changelog about the new gradle versions?

**Comment by cdietrich** [comment]
would be nice, yes

**Comment by jonahgraham** [comment]
> would be nice, yes

I have just noticed you merged this. Do you still need a review, or are you satisfied with the change?

**Comment by cdietrich** [comment]
I assume it works but if you still can do a diff it would be nice.

**Comment by jonahgraham** [comment]
The diff looks basically identical to me. I think that makes sense as even though version of Gradle changed, version of Bnd stayed the same. I compared build output of [build 63](https://ci.eclipse.org/lsp4j/job/lsp4j-multi-build/job/main/63/artifact/) vs [build 64](https://ci.eclipse.org/lsp4j/job/lsp4j-multi-build/job/main/64/artifact/)

**Pull request merged**
