### PR TITLE
Add new file operation events

### PR DESCRIPTION
**Pull request by KamasamaK**
Add support for file operation events (create, rename, delete) introduced with LSP 3.16

### CODE REVIEW

**Comment by ericdallo** [comment]
@KamasamaK could we have a release with this change?

**Comment by KamasamaK** [comment]
@ericdallo I'm just a committer. That would be up to the [project leads](https://projects.eclipse.org/projects/technology.lsp4j/who).

**Comment by jonahgraham** [comment]
I am waiting for someone to confirm that 3.16 support is ready for release. I sent an email to lsp4j-dev to make sure the request is visible, and we can do the release soon. 

@KamasamaK project leads aren't special in regard to making a release. Consensus should generally be obtained, but no special status of project lead exists as far as making a release is concerned. Traditionally project leads do make sure that releases are done, but you should feel empowered to propose (and even make) a release whenever you see fit. 

From [EDP](https://www.eclipse.org/projects/dev_process/#4_6_2_PL) 

> Project Leads are responsible for ensuring that their Project’s Committers are following the Eclipse Development Process, and that the Project is engaging in the right sorts of activities to develop vibrant communities of users, Adopters, and Contributors.

**Comment by ericdallo** [comment]
Thanks @jonahgraham!

**Comment by nixel2007** [comment]
It would be nice if #481 and #480 will be included in 0.11.

**Pull request merged**
